# -*- coding: utf-8 -*-
"""Wandb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DWDF8WxdsCOy2jQ_Sv55j4I4byx-ixb
"""


import wandb
wandb.login()

import wandb
from ultralytics import YOLO

# Setup wandb project
wandb.init(
    project="New_yolov8n_bottle_project",
    name="yolov8n-colab",
    config={
        "model": "yolov8n",
        "epochs": 100,
        "batch": 16,
        "imgsz": 640
    }
)

# Load model
model = YOLO("yolov8n.pt")

# Training
model.train(
    data="/content/bottle.yaml",
    epochs=100,
    batch=16,
    imgsz=640,
    project="New_yolov8n_bottle_project",
    name="caps_nano_run",
)

wandb.finish()
